services:
  app:
    image: utilwed7539/yalmt:latest
    container_name: yalmt-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - DB_URL=${DB_URL}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AZURE_BLOB_CON=${AZURE_BLOB_CON}

  redis:
    image: redis:7
    container_name: my-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}